# Generated by Django 3.0.7 on 2021-04-13 15:11

import Generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0003_auto_20210413_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='core_competencies_json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=Generator.models.OverwriteStorage(), upload_to='Generator/CoreCompetenciesJSONs/')),
            ],
            options={
                'verbose_name': 'Core Competencies JSON file',
                'verbose_name_plural': 'Core Competencies JSON files',
            },
        ),
    ]
