# Generated by Django 3.0.7 on 2021-03-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0006_auto_20200325_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelshSkillsJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Welsh Skills JSON file',
                'verbose_name_plural': 'Welsh Skills JSON files',
            },
        ),
        migrations.AlterModelOptions(
            name='skilljson',
            options={'verbose_name': 'Skills JSON file', 'verbose_name_plural': 'Skills JSON files'},
        ),
    ]
