# Generated by Django 3.0.7 on 2021-03-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0008_welshlevel_welshskill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WelshLevel',
            new_name='cy_Level',
        ),
        migrations.RenameModel(
            old_name='WelshSkill',
            new_name='cy_Skill',
        ),
        migrations.RenameModel(
            old_name='WelshSkillsJSON',
            new_name='cy_SkillJSON',
        ),
    ]
