# Generated by Django 3.0.7 on 2021-03-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0009_auto_20210325_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cy_level',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Generator.cy_Skill'),
        ),
    ]
